city_hash_array = [{:city=>"Cupertino", :state=>"California"},
  {:city=>"Bethesda", :state=>"Maryland"},
  {:city=>"Greenwich", :state=>"Connecticut"},
  {:city=>"Mound", :state=>"Texas"},
  {:city=>"Burke", :state=>"Virginia"},
  {:city=>"Township", :state=>"Michigan"},
  {:city=>"Marin", :state=>"California"},
  {:city=>"Pleasanton", :state=>"California"},
  {:city=>"Alto", :state=>"California"},
  {:city=>"Linda", :state=>"California"},
  {:city=>"Naperville", :state=>"Illinois"},
  {:city=>"Ranch", :state=>"Colorado"},
  {:city=>"Newton", :state=>"Massachusetts"},
  {:city=>"Woodlands", :state=>"Texas"},
  {:city=>"Milpitas", :state=>"California"},
  {:city=>"Wayne", :state=>"New"},
  {:city=>"Fairfield", :state=>"Connecticut"},
  {:city=>"Beach", :state=>"California"},
  {:city=>"Cobb", :state=>"Georgia"},
  {:city=>"Huntington", :state=>"New"},
  {:city=>"Clarkstown", :state=>"New"},
  {:city=>"Verdes", :state=>"California"},
  {:city=>"Land", :state=>"Texas"},
  {:city=>"Plateau", :state=>"Washington"},
  {:city=>"Hempstead", :state=>"New"},
  {:city=>"Niguel", :state=>"California"},
  {:city=>"Smithtown", :state=>"New"},
  {:city=>"Greenburgh", :state=>"New"},
  {:city=>"Trabuco", :state=>"California"},
  {:city=>"Reston", :state=>"Virginia"}]
5.times do
  @article = Article.create(title: ShakespeareIpsum.insult!, body: ShakespeareIpsum::Sonnets.sonnet, author: ShakespeareIpsum::Name.name, city: "#{city_hash_array.sample[:city]}, #{city_hash_array.sample[:state]}")
end
